language: python
python:
    - 2.7
    - 3.5

cache:
    directories:
        - $HOME/.cache/pip


install:
    - pip install -U pip
    - pip install flake8
    - pip install -r requirements.txt

script:
    - flake8 letsencrypt-aws.py
